source :rubygems

#gem "rack"
#gem "rake"                # actually not need for heroku but for the provided Rakefile
gem "RedCloth"            # if you want to use the Textile Markup Language
#gem "jekyll", "~> 2.5.3” # we need at least this version so jekyll will use Ruby 1.9.2
gem 'rack-jekyll', :git => 'https://github.com/adaoraul/rack-jekyll.git', :require => 'rack/jekyll'
#gem "foreman"             # this is a tool to test and use the Procfile locally
